tomastrajan/angular-ngrx-material-starter

package.json
src/index.html
src/styles-variables.scss
src/styles.scss

Fix 404 error when trying to load some font files of Font Awesome from CDN.
Used NPM version instead.

fix(dependency): use font-awesome from npm

---

src/app/examples/todos/todos.reducer.ts

*Problem:* the changed items in the array are not being recreated. Instead, [the shallow copy of ```items``` object is being produced](https://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html#updating-nested-objects) and they are being mutated by  ```item.done = !item.done ```. 
*Solution:* use ```map``` to produce a new array and create a new object for every toggled/untoggled item.

fix(todos): eliminate input mutation from the reducer

---

e2e/app.e2e-spec.ts
e2e/app.po.ts

Currently, when you clone from master and run `ng e2e` you get the error:  `Failed: No element found using locator: By(css selector, app-root h1)`. 
This simple PR just fixes the e2e test to find the correct element and expect a different value of text.

Fix E2E Tests

---

src/app/app.component.ts
src/index.html

In order to track each view as a 'pageview' in Google Analytics, we need to subscribe to the router `NavigationEnd` event and manually set the pageview for each application view.
#173

fix(app): track pageviews in Google Analytics

---

package-lock.json
package.json

When we make a commit all files are getting formatted with prettier, even the unmodified ones.
Also after they have been formatted they won't automatically be added to the commit.
This PR changes this behavior and will only format the modified files and will also add the formatted file to the commit , following the [prettier guide](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged).

chore: add lint-staged to only format modified files

---

src/app/app.component.ts
src/app/core/auth/auth-guard.service.ts
src/app/core/auth/auth.actions.ts
src/app/core/auth/auth.effects.ts
src/app/core/auth/auth.models.ts
src/app/core/auth/auth.reducer.ts
src/app/core/auth/auth.selectors.ts
src/app/core/core.module.ts
src/app/core/core.state.ts
src/app/core/index.ts
src/app/core/meta-reducers/debug.reducer.ts
src/app/core/meta-reducers/init-state-from-local-storage.reducer.ts
src/app/examples/examples.state.ts
src/app/examples/examples/examples.component.ts
src/app/examples/stock-market/components/stock-market-container.component.spec.ts
src/app/examples/stock-market/components/stock-market-container.component.ts
src/app/examples/todos/components/todos-container.component.spec.ts
src/app/examples/todos/components/todos-container.component.ts

This PR adds an `AppState` to the application.
In order to make this possible I also split up the `auth` reducer, as @tomastrajan previously did for the example states.
What still has to be done is the verification that there is no unexpected appstate in the feature module's bundle with `npm run analyze`. I have taken a look and I think it should be OK, but please do verify it because this was new to me 😅 .
Closes #304

refactor(Core): Add App state

---

src/app/core/auth/auth-guard.service.ts
src/app/examples/examples/examples.component.html
src/app/examples/examples/examples.component.ts

@matiasiglesias @Jeykairis adjusted the auth guard and introduced `auth` flag for menu items that should be available only for authenticated users. This could be changed in the future into roles so instead of boolean flag it can be a role name array...

refactor(auth): use observable in auth guard

---

src/app/core/auth/auth.selectors.spec.ts
src/app/core/auth/auth.selectors.ts

There is really no difference between selectAuth and selectAuthState, both are memoized selectors and they are returning the same values.
I did just add another selector for good practice, even though the AuthState is very small, so today there is no practical difference. Therefore I did not take it upon myself to change code where selectAuth is used.
But if the scenario instead would be
`auth: {
isAuthenticated: false,
someOtherProp: false
}`
and you only are interested in isAuthenticated. The selectAuth would result in multiple subscription triggers if someOtherProp would change. 
Issue number: #336

test(auth): add unit test for auth selectors, closes #336

---

src/app/examples/stock-market/stock-market.effects.spec.ts
src/app/examples/stock-market/stock-market.effects.ts
tslint.json

I wrote the tests without the TestBed as advised by Viktor Savkin in this example [repo](https://github.com/vsavkin/testing_ngrx_effects). If you feel that the tests should use TestBed I can refactor it without a problem.
I refactored the `retrieveStock` effect into a function, which allows for easier overrides of the debounceTime value and scheduler during testing. It follows the official effects testing [guide](https://github.com/ngrx/platform/blob/master/docs/effects/testing.md#effects-as-functions).
Finally, I fixed a bug with `distinctUntilChanged()` operator. Let me demonstrate it with the example:
Assuming we dispatch the following actions: 
```
{ type: 'RETRIEVE', payload: { symbol: 'TSLA' } }
{ type: 'RETRIEVE', payload: { symbol: 'TSLA' } }
{ type: 'RETRIEVE', payload: { symbol: …
```

test(stock-market): add stock market effects spec, closes #267

---

src/app/app.component.scss-theme.scss
src/app/app.component.ts
src/app/core/core.module.ts
src/app/core/error-handler/app-error-handler.service.ts
src/app/core/http-interceptors/http-error.interceptor.ts
src/app/core/http-interceptors/index.ts
src/app/core/local-storage/local-storage.service.spec.ts
src/app/core/local-storage/local-storage.service.ts
src/app/examples/stock-market/stock-market.service.spec.ts

Added application-wide error handler that shows a UI notification
for any client or HTTP error before passing the error to
the default Angular ErrorHandler.
closes #321
Please see #360 for review comments for the previous version of my changes.

feat(): add UI notification for client and HTTP errors

---

src/app/app.component.scss

I changed overflow-y axis from auto to hidden. And also I changed overflow-x and -y to one overflow property.
I checked if it works correctly in Chrome, IE and Edge.
Issue number:  #400

fix(app): Double scrollbar on page transition in long pages. fixes #400

---

Production.Dockerfile
Production.docker-compose.yml
README.md
package.json
server.js

* A `Production.Dockerfile` with 3 stages:
* `npm_builder` so that docker can cache the `npm install` command so it is not re-run every time you make small code changes. 
* `builder` which will run `build:prod`
* `production` which is the final image and will take a fresh `node:11.1.0` image, copy the necessary files from the `builder` stage and then run `node server.js`
* A `Production.docker-compose.yml` which can be used to run and build the `Production.Dockerfile`. This can be run with `docker-compose -f Production.docker-compose.yml up`
* Updates to `server.js` which will take the port and context from environment variables, if those variables exist. Should not be a breaking change.
* An update to remove the / and append it on CONTEXT instead so that I can control click the url from …

feat(docker): dockerfile for production

---

src/styles-reset.scss
src/styles-variables.scss

Since the following PR https://github.com/twbs/bootstrap/pull/25561, there is a variable for setting the label's margin-bottom. We don't need to manually reset it.

refactor(styles): simplify the label's margin-bottom reset

---

src/app/core/google-analytics/google-analytics.effects.spec.ts
src/app/examples/examples.effects.spec.ts
src/app/settings/settings.actions.spec.ts
src/app/settings/settings.reducer.spec.ts

Add tests for  settings actions and reducers, examples effects and google-analytics effects.
@timdeschryver, wasn't able to test the `changeLanguage` effect from the examples module.
Could you provide some guidance on that please?

test(app):  settings, examples and google-analytics tests, closes #419

---

package-lock.json
package.json

Due to a malicious dependency `flatmap-stream` within cypress 3.1.1 we had to update package.json to cypress 3.1.2 or higher which has fixed this vulnerability (see https://github.com/cypress-io/cypress/issues/2861).  
Closes #437

cypress package version updated

---

projects/angular-ngrx-material-starter/src/app/features/examples/form/components/form.component.spec.ts
projects/angular-ngrx-material-starter/src/app/features/examples/todos/components/todos-container.component.spec.ts

The tests for the FormComponent and the ToDo Component are migrated to the new material test harness. 
If these are OK, i would also migrate the other components. 
Issue number: #513

Migration Angular Material Test Harness

---

projects/angular-ngrx-material-starter/e2e/protractor.conf.js
projects/angular-ngrx-material-starter/e2e/src/setup.ts
projects/angular-ngrx-material-starter/src/app/core/settings/settings.effects.spec.ts
projects/angular-ngrx-material-starter/src/app/core/settings/settings.effects.ts

Closes #511 
Issue number: #511

fix(change-hours): run change hours interval outside of angular zone

---

projects/angular-ngrx-material-starter/src/app/features/feature-list/feature-list.data.ts

Update the Bootstrap documentation link to (4.0 -> 4.4) better match the version package dependencies (`"bootstrap": "^4.4.1",`) & documentation path from `../layout/grid/` to `../getting-started/introduction/`

docs(features): update bootstrap doc. link

---

projects/angular-ngrx-material-starter/src/app/app/app.component.ts
projects/angular-ngrx-material-starter/src/app/features/about/about/about.component.ts

Set relative src path for assets in order to work properly on github pages.
This fixes the following:

fix: set correct, relative, src paths for assets

---

package.json

fix: set base href with trailing slash for production build
- in order to use relative path urls, the base-href tag has to be set with a trailing slash, e.g. `<base href="some_path/" />`
- for more information see [Stackoverflow Answer](https://stackoverflow.com/a/26043021/13226740) 
- tldr see screenshot:
see discussion in previous [PR](https://github.com/tomastrajan/angular-ngrx-material-starter/pull/551) 
assets path urls, such as the logo, the favicon or images on "about" page
i18n files, that are also delivered from "assets" folder
the hash-routing was not the problem, but it isn't needed anymore to make the app work on GH pages --> I could do another PR to change this, if you like

fix: base href

---

projects/angular-ngrx-material-starter/src/app/app-routing.module.ts

Remove hash location opt in.
- hash location strategy is no longer necessary to work with GiiHub Pages
- see test deployment from forked repo: https://tino-tg.github.io/angular-ngrx-material-starter - of course i will remove the deployment after the PR is merged 
- for further information check out the [docs](https://angular.io/guide/router#locationstrategy-and-browser-url-styles)
Issue number: see diescussion in [previous PR](https://github.com/tomastrajan/angular-ngrx-material-starter/pull/552)

feat: remove hash location opt in
