- src/app/shared/big-input/big-input-action.component.ts
- src/app/shared/big-input/big-input.component.ts
... for 
- BigInputComponent
- BigInputActionComponent
Also changed `SharedModule` import path.  The old one was  not working in my IDE (VS Code on Windows).
> Changed changeDetection to OnPush

- e2e/src/about/about.e2e-spec.ts
- e2e/src/about/about.po.ts
- e2e/src/app.e2e-spec.ts
- e2e/src/app.po.ts
- e2e/src/utils/index.ts
replaced  excessive 'return's by short arrow function shape
> feat(e2e): #178 add tests for app and about page

- README.md
Update README.md: Replace `BUILD_WITH` to `BUILT_WITH` to reflect name of the referenced file.
> docs(typo) Update README: BUILD_WITH to BUILT_WITH

- src/app/examples/todos/todos.component.spec.ts
added all "TODO"s expect the first one - cannot get menu show the menupopup
> feat(todo): create tests for todos container [added more TODOS] (#219)

- package-lock.json
- src/app/settings/settings/settings.component.spec.ts
question: may be it is good thing to transfer the 'ActionSettingsPersist' action to be called from 'effect'?
> feat(tests): for settings component #244

- src/app/shared/big-input/big-input.component.spec.ts
> test(BigInputComponent): created unit test for BigInputComponent

- src/app/settings/settings.reducer.spec.ts
> test(settings): Added settingsReducer unit tests

- src/app/settings/settings.reducer.spec.ts
> fix(settings): added Change Language test

- src/app/examples/stock-market/components/stock-market-container.component.spec.ts
> test(StockMarket): mock retrieveStock during tests

- src/app/app.component.ts
- src/app/settings/components/settings-container.component.ts
- src/app/settings/settings.model.ts
- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/assets/i18n/examples/pt-br.json
- src/assets/i18n/fr.json
- src/assets/i18n/pt-br.json
- src/assets/i18n/sk.json
This adds Portuguese from Brazil translate.
> feat(i18n): add portuguese brazil translations

- src/app/examples/todos/components/todos-container.component.ts
- src/assets/i18n/examples/de.json
- src/assets/i18n/examples/en.json
- src/assets/i18n/examples/es.json
- src/assets/i18n/examples/fr.json
- src/assets/i18n/examples/pt-br.json
- src/assets/i18n/examples/sk.json
added translation for all snackbar messages,
on filter, toggle, added, and removed
fixes #324
> fix(todos): snackbar not being translated

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
Add some a bug report and a feature request template for issues.
Add a pull request template.
> Add github templates

- src/app/core/auth/auth.effects.spec.ts
> test(auth): add unit tests for autheffects, closes #335

- src/app/examples/form/components/form.component.ts
- src/app/examples/form/form.actions.spec.ts
- src/app/examples/form/form.model.ts
- src/app/examples/form/form.reducer.spec.ts
- cleanup unused imports/variables
- add `autosave` to the form model (because it's also getting saved and loaded with local storage)
- use `take(1)` instead of `unsubscribe`
cc: @Jeykairis 
Issue number: /
> refactor(Form): cleanup

- .github/ISSUE_TEMPLATE.md.md
- .github/PULL_REQUEST_TEMPLATE.md
> chore: reword how to add yourself as a contributor and add issue template

- src/app/examples/crud/components/crud.component.ts
Emit on destroy to close all open subscriptions in crud component.
> Fix memory leak in crud component

- angular.json
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.scss-theme.scss
- src/app/examples/crud/components/crud.component.scss
- src/app/examples/examples/examples.component.html
- src/app/examples/examples/examples.component.scss
- src/app/examples/examples/examples.component.scss-theme.scss
- src/app/examples/form/components/form.component.html
- src/app/examples/todos/components/todos-container.component.html
- src/app/settings/components/settings-container.component.html
- src/app/static/features/features.component.html
- src/assets/i18n/examples/de.json
- src/assets/i18n/examples/en.json
- src/assets/i18n/examples/es.json
- src/assets/i18n/examples/fr.json
- src/assets/i18n/examples/pt-br.json
- src/assets/i18n/examples/sk.json
- src/index.html
- src/styles-app-loading.scss
Some cosmetic changes to make the starter looks better with every languages on every screen sizes.
> fix(ui): Cosmetic changes to improve responsive translated views

- src/app/examples/stock-market/stock-market.reducer.spec.ts
Unit tests for `stock-market.reducer`.
Issue number: #266
> test(examples): create unit tests for stock market reducer #266

- .gitignore
- README.md
- cy-server.js
- cypress.json
- cypress/integration/about.spec.ts
- cypress/integration/app.spec.ts
- cypress/plugins/cy-ts-preprocessor.js
- cypress/plugins/index.js
- cypress/support/index.ts
- cypress/tsconfig.json
- package-lock.json
- package.json
- src/app/app.component.html
- src/app/static/about/about.component.html
- src/app/static/features/features.component.html
- src/assets/i18n/en.json
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
Introduces cypress to run our e2e tests.
- cypress config and npm scripts are added
- protractor tests are rewritten
- `data-testid` attributes are added in the html to use in the tests, prettier also formatted these files
> [WIP] add cypress

- src/app/static/features/features.component.html
Repare the merge adding fa-icons for the new cypress feature.
> Repare the merge adding fa-icons for the new cypress feature

- src/app/core/auth/auth.reducer.spec.ts
Added unit test for AuthReducer
Issue number: #334
> test(auth): Added unit test for auth reducer, closes #334

- src/app/core/auth/auth.actions.spec.ts
Added unit test for Auth Actions.
Issue number: #333
> test(auth): add unit tests for auth actions, closes #333

- src/app/examples/crud/books.effects.spec.ts
Add tests for the BooksEffects.
Use the `MockStore` to provide a Store instance for the effect to use `withLatestFrom`.
Issue number: #339
> test(crud): add unit tests for BooksEffects, closes #339

- src/app/core/auth/auth-guard.service.spec.ts
Add tests for the AuthGuardService.
Issue number: #337
> test(auth): add unit tests for AuthGuardService, closes #337

- src/app/settings/settings.actions.spec.ts
Add specs for settings actions
Issue number: #338
> test(settings): add unit tests for settings actions, closes #338

- src/app/examples/form/components/form.component.ts
- src/app/examples/form/form.effects.ts
Restore the form state consistently with the local storage.
> fix(form): restore the form state consistently with the local storage

- README.md
Add a point to the "Make It Your Own" section of the README
> Add a point to the "Make It Your Own" section of the README

- src/app/examples/todos/components/todos-container.component.html
- src/assets/i18n/examples/de.json
- src/assets/i18n/examples/en.json
- src/assets/i18n/examples/es.json
- src/assets/i18n/examples/fr.json
- src/assets/i18n/examples/pt-br.json
- src/assets/i18n/examples/sk.json
Added use case of ngPlural directive usage in todos filter template and added translations.
Issue number: #362
> fix(todos): add ngPlural todos filter description, fixes #362

- package-lock.json
- package.json
- src/app/core/auth/auth.selectors.spec.ts
- src/app/core/core.module.ts
- src/app/core/core.state.ts
- src/app/core/index.ts
- src/app/core/router/custom-serializer.ts
- src/app/core/router/router.state.ts
- src/app/examples/crud/books.actions.spec.ts
- src/app/examples/crud/books.actions.ts
- src/app/examples/crud/books.effects.spec.ts
- src/app/examples/crud/books.effects.ts
- src/app/examples/crud/books.model.ts
- src/app/examples/crud/books.reducer.spec.ts
- src/app/examples/crud/books.reducer.ts
- src/app/examples/crud/books.selectors.ts
- src/app/examples/crud/components/crud.component.html
- src/app/examples/crud/components/crud.component.spec.ts
- src/app/examples/crud/components/crud.component.ts
- src/app/examples/examples-routing.module.ts
- src/app/examples/examples.module.ts
- src/app/examples/examples.state.ts
- src/assets/i18n/examples/en.json
- src/assets/i18n/examples/fr.json
The goal is to use ngrx-router-store to get the selected book from the url.
Issue number: 331
> Use @ngrx-router-store #331

- README.md
Add recently implemented @ngrx features to the README.
> docs(readme): Add new @ngrx features

- src/app/examples/todos/todos.effects.spec.ts
Refactored todos effects specs as discussed in #389
> test(todos): remove TestBed from todos effects specs

- src/app/examples/form/form.effects.spec.ts
Add missing form effects tests
> test(form): add form effects tests

- src/app/settings/settings.effects.spec.ts
Refactored settings effects specs as discussed in #389
> test(settings): remove TestBed from settings effects specs

- .prettierrc
- tslint.json
> Remove redundant rules from tslint.json, fixes #391

- .dockerignore
- Dockerfile
- README.md
- package.json
Ability to run project inside docker container #385 
> feat(docker): ability to project inside container

- src/app/app.component.scss-theme.scss
- src/app/core/core.module.ts
- src/app/core/error-handler/app-error-handler.service.ts
- src/app/core/notifications/notification.service.spec.ts
- src/app/core/notifications/notification.service.ts
- src/app/examples/examples-routing.module.ts
- src/app/examples/examples.module.ts
- src/app/examples/examples/examples.component.ts
- src/app/examples/form/components/form.component.spec.ts
- src/app/examples/form/components/form.component.ts
- src/app/examples/notifications/components/notifications.component.html
- src/app/examples/notifications/components/notifications.component.scss-theme.scss
- src/app/examples/notifications/components/notifications.component.spec.ts
- src/app/examples/notifications/components/notifications.component.ts
- src/app/examples/todos/components/todos-container.component.spec.ts
- src/app/examples/todos/components/todos-container.component.ts
- src/assets/i18n/examples/en.json
- src/styles-variables.scss
- src/styles.scss
Provides a consistent mechanism for displaying self-closing Error, Warning, and Information notifications.
closes #377
> refactor(notifications): Implemented UI Notifications Service

- .gitignore
- README.md
- package-lock.json
- package.json
Added  [Compodoc](https://compodoc.app/) to generate a static app documentation.
The documentation will be generated by running the script `npm run compodoc`, which creates a directory `documentation`.
> Added Compodoc to generate a static app documentation

- package-lock.json
- package.json
- src/app/examples/form/components/form.component.spec.ts
Added a happy path test for the form example.
This is done with [ngx-test-library](https://github.com/timdeschryver/ngx-testing-library).
> test(Form): add happy path

- src/app/examples/form/components/form.component.spec.ts
- src/app/examples/todos/components/todos-container.component.html
- src/app/examples/todos/components/todos-container.component.spec.ts
- src/app/examples/todos/components/todos-container.component.ts
- src/app/examples/todos/todos.selectors.ts
- src/app/shared/big-input/big-input-action.component.html
- src/app/shared/big-input/big-input-action.component.ts
- introduce todos selectors (and the `async` pipe)
- Rewrite tests using @angular-extensions/testing-library
> refactor: introduce todos selectors

- e2e/protractor.conf.js
- e2e/src/about/about.po.ts
- e2e/src/setup.ts
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/examples/examples.effects.ts
- src/app/examples/examples.module.ts
- src/app/examples/examples/examples.component.html
- src/app/examples/examples/examples.component.ts
- src/app/settings/settings.effects.spec.ts
- src/app/settings/settings.effects.ts
- src/app/settings/settings.selectors.ts
> fix(ngrx): fix e2e / cypress tests, refactor effects

- src/assets/i18n/de.json
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/assets/i18n/fr.json
- src/assets/i18n/he.json
- src/assets/i18n/pt-br.json
- src/assets/i18n/sk.json
- src/assets/i18n/zh-cn.json
> fix(i18n): fix missing label #549

- BUILT_WITH.md
Added REQLoot project built with help of Angular, ngrx and Angular Material Starter
> docs(builtWith): added project built with ngrx material starter

- projects/angular-ngrx-material-starter/src/app/app/app.component.ts
- projects/angular-ngrx-material-starter/src/app/core/auth/auth.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/core/auth/auth.actions.ts
- projects/angular-ngrx-material-starter/src/app/core/auth/auth.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/core/auth/auth.effects.ts
- projects/angular-ngrx-material-starter/src/app/core/auth/auth.reducer.spec.ts
- projects/angular-ngrx-material-starter/src/app/core/auth/auth.reducer.ts
- projects/angular-ngrx-material-starter/src/app/core/core.module.ts
Issue number: handles `auth` for #472
> refactor: use ngrx create functions for auth

- projects/angular-ngrx-material-starter/src/app/features/examples/todos/components/todos-container.component.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/components/todos-container.component.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/todos.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/todos.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/todos.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/todos.effects.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/todos.reducer.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/todos.reducer.ts
> refactor: use ngrx create functions for todo

- package-lock.json
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.effects.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.reducer.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.reducer.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/components/crud.component.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/components/form.component.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/components/form.component.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.effects.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.reducer.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.reducer.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/components/stock-market-container.component.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/components/stock-market-container.component.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/stock-market.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/stock-market.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/stock-market.effects.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/stock-market.reducer.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/stock-market.reducer.ts
Issue number: https://github.com/tomastrajan/angular-ngrx-material-starter/issues/472
Integrated the new features of Ngrx 7 into the examples folder. Effects, reducers as well as actions were refactored to accommodate for the new changes.
> feat: ngrx 8 refactor

- projects/angular-ngrx-material-starter/src/app/app/app.component.ts
- projects/angular-ngrx-material-starter/src/app/core/core.module.ts
- projects/angular-ngrx-material-starter/src/app/core/settings/settings.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/core/settings/settings.actions.ts
- projects/angular-ngrx-material-starter/src/app/core/settings/settings.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/core/settings/settings.effects.ts
- projects/angular-ngrx-material-starter/src/app/core/settings/settings.reducer.spec.ts
- projects/angular-ngrx-material-starter/src/app/core/settings/settings.reducer.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/crud/books.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/examples.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/examples.effects.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/form/form.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/stock-market.actions.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/stock-market/stock-market.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/todos.actions.ts
- projects/angular-ngrx-material-starter/src/app/features/settings/settings/settings-container.component.spec.ts
- projects/angular-ngrx-material-starter/src/app/features/settings/settings/settings-container.component.ts
Refactor settings ngrx functions to ngrx 8.
Issue number: https://github.com/tomastrajan/angular-ngrx-material-starter/issues/472
> refactor(settings): refactored to ngrx 8

- projects/angular-ngrx-material-starter/src/app/core/google-analytics/google-analytics.effects.spec.ts
- projects/angular-ngrx-material-starter/src/app/core/google-analytics/google-analytics.effects.ts
Refactor Google Analytics Service to Ngrx 8
Issue number: #472
> refactor(google-analytics): refactor to ngrx 8

- CONTRIBUTING.md
> docs(contributing): typo fix

- projects/angular-ngrx-material-starter/src/assets/i18n/de.json
- projects/angular-ngrx-material-starter/src/assets/i18n/en.json
- projects/angular-ngrx-material-starter/src/assets/i18n/es.json
- projects/angular-ngrx-material-starter/src/assets/i18n/fr.json
- projects/angular-ngrx-material-starter/src/assets/i18n/he.json
- projects/angular-ngrx-material-starter/src/assets/i18n/pt-br.json
- projects/angular-ngrx-material-starter/src/assets/i18n/sk.json
- projects/angular-ngrx-material-starter/src/assets/i18n/zh-cn.json
> refactor(settings): added missing Hebrew language label to the JSON's

- .all-contributorsrc
- README.md
- projects/angular-ngrx-material-starter/src/app/features/about/about/about.component.html
- projects/angular-ngrx-material-starter/src/app/features/examples/simple-state-management/components/user.component.html
Firstly I would like to thank you for this quality work,
I found a malfunction of the inputs on the simple-state-management part in the example module.
The error message was configured badly in the html file for the inputs : name + surname.
I fixed it and this is my first pull request 👍 
Regards
> Simple state management error refactor

- BUILT_WITH.md
We wanted to add our web page here to inspire others, how angular-ngrx-material-starter repo helped us to start our full up and running blog !!
> Added Universal Tutorial to the Project List

- .all-contributors-html.js
- .all-contributorsrc
- README.md
- projects/angular-ngrx-material-starter/src/app/app/app.component.html
- projects/angular-ngrx-material-starter/src/app/features/about/about/about.component.html
- projects/angular-ngrx-material-starter/src/app/features/examples/elements/elements.component.html
- projects/angular-ngrx-material-starter/src/app/features/examples/simple-state-management/components/user.component.html
- projects/angular-ngrx-material-starter/src/app/features/feature-list/feature-list/feature-list.component.html
When a link opens a URL in a new tab with target="_blank", it is very simple for the opened page to change the location of the original page because the JavaScript variable window.opener is not null and thus "window.opener.location can be set by the opened page. This exposes the user to very simple phishing attacks.
To prevent pages from abusing window.opener, use rel=noopener on <a href=> to force its value to be null on the opened pages. With this in place, window.opener is null in Chrome 49+, Opera 36+, Firefox 52+, Desktop Safari 10.1+, and iOS Safari 10.3+. For older browsers, use "noreferrer". Cumulatively, rel="noopener noreferrer" is the safest way to mitigate this vulnerability.
> Added rel="noopener noreferrer" in anchor and alt in image tag

- projects/angular-ngrx-material-starter/src/assets/i18n/zh-cn.json
Fixed a typo in Chinese translation.
> fix: typo in the zh-cn translation for `vector`

- projects/angular-ngrx-material-starter/src/app/features/examples/todos/components/todos-container.component.html
- projects/angular-ngrx-material-starter/src/app/features/examples/todos/components/todos-container.component.ts
> fix(#524): class active on Todos filter not showing up

- README.md
> fix(#556): fix link in README
